name: Lint
on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nebularg/actions-luacheck@v1
        with:
          args: '-q --formatter plain --no-cache'
          annotate: 'warning'
