name: optional
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  INSTALL_PREFIX: ${{ github.workspace }}/nvim-install
  # Double test timeout since it's running via qemu
  TEST_TIMEOUT: 2400
  # TEST_FILE: test/functional/shada
  # TEST_FILTER: foo

jobs:
  s390x:
    if: contains(github.event.pull_request.labels.*.name, 'ci-s390x') || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        test: [functionaltest, oldtest]
    env:
      TARGET: ${{ matrix.test }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: actions/checkout@v4
      - uses: docker://multiarch/ubuntu-core:s390x-focal
        with:
          entrypoint: ./.github/scripts/docker-action.sh
  armhf:
    if: contains(github.event.pull_request.labels.*.name, 'ci-armhf') || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        test: [functionaltest, oldtest]
    env:
      TARGET: ${{ matrix.test }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: actions/checkout@v4
      - uses: docker://multiarch/ubuntu-core:armhf-focal
        with:
          entrypoint: ./.github/scripts/docker-action.sh
